condition <- factor(c("Wt","Wt","Buc","Buc","dndMo","dndMo"))
#condition <- factor(rep(c("DMSO","EM"),each=3))
condition
coldata<- as.data.frame(condition)
rownames(coldata) <- colnames(pgc_count)
coldata
library("DESeq2")
dds_pgc<- DESeqDataSetFromMatrix(countData = pgc_count,
                                colData = coldata,
                                design = ~ condition)
dds_pgc
dds2_pgc <- DESeq(dds_pgc)
resultsNames(dds2_pgc)
res_dnd_buc <- results(dds2_pgc,contrast=c("condition","dndMo","Buc"))
res_wt_dnd <- results(dds2_pgc, contrast=c("condition","Wt","dndMo"))
res_wt_buc <- results(dds2_pgc, contrast=c("condition","Wt","Buc"))

nor_pgc <- as.data.frame(counts(dds2_pgc,normalized=T))
write.table(nor_pgc,"~/Cooperation_PGCs/nor_pgc.txt",col.names=T,row.names=T,quote=F,sep="\t")
diff_dnd_buc <- subset(res_dnd_buc, padj < 0.05 & (log2FoldChange > 0 |log2FoldChange < 0))
diff_dnd_buc <- as.data.frame(diff_dnd_buc)
write.table(diff_dnd_buc,"~/Cooperation_PGCs/diff_dnd_buc.txt",col.names=T,row.names=T,quote=F,sep="\t")
diff_wt_dnd <- subset(res_wt_dnd, padj < 0.05 & (log2FoldChange > 0 |log2FoldChange < 0))
diff_wt_dnd <- as.data.frame(diff_wt_dnd)
write.table(diff_wt_dnd,"~/Cooperation_PGCs/diff_wt_dnd.txt",col.names=T,row.names=T,quote=F,sep="\t")
diff_wt_buc <- subset(res_wt_buc, padj < 0.05 & (log2FoldChange > 0 |log2FoldChange < 0))
diff_wt_buc <- as.data.frame(diff_wt_buc)
write.table(diff_wt_buc,"~/Cooperation_PGCs/diff_wt_buc.txt",col.names=T,row.names=T,quote=F,sep="\t")
diff_dnd <- subset(res_dnd_buc, padj < 0.05 & log2FoldChange > 0 )
diff_dnd <- as.data.frame(diff_dnd)
dnd<- mutate(diff_dnd,GeneID=rownames(diff_dnd))
dnd_list <- as.character(dnd$GeneID)
BP_dnd <- enrichGO(gene=dnd_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
barplot(BP_dnd,showCategory=15)

diff_buc <- subset(res_dnd_buc, padj < 0.05 & log2FoldChange < 0 )
diff_buc <- as.data.frame(diff_buc)
buc<- mutate(diff_buc,GeneID=rownames(diff_buc))
buc_list <- as.character(buc$GeneID)
BP_buc <- enrichGO(gene=buc_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
barplot(BP_buc,showCategory=15)
cg=names(tail(sort(apply(nor_pgc,1,sd)),1000))
pheatmap(log2(nor_pgc[cg,]+1),show_rownames = F,annotation_col = ac)
t <- nor_pgc
pca <- prcomp(t, scale. = TRUE)
pca$rotation
ggbiplot(pca,ellipse=T,circle = TRUE)
pheatmap(cor(nor_pgc),
         display_numbers = T)
hc=hclust(dist(t(nor_pgc)))
dnd_buc <- mutate(diff_dnd_buc,GeneID=rownames(diff_dnd_buc))
dnd_buc_list <- as.character(dnd_buc$GeneID)
ah_all <- AnnotationHub(localHub=TRUE)
subset(ah_all,species=='Danio rerio'&rdataclass=='OrgDb')
dotplot(all_dnd_buc,split='ONTOLOGY')+facet_grid(ONTOLOGY~.,scale='free')
ath_all <- ah_all[['AH66164']]
go_dnd_buc <- AnnotationDbi::select(ath_all,keys=dnd_buc_list,columns=c("ENSEMBL","SYMBOL"),keytype="ENSEMBL")
BP_dnd_buc <- enrichGO(gene=dnd_buc_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
emapplot(BP_dm32)
MM <- setReadable(BP_dm32, OrgDb = ath_all,keytype = "EMSEMBL")
cnetplot(MM, categorySize="pvalue", foldChange=diff_32$log2FoldChange)
uni_dnd_buc <- AnnotationDbi::select(ath_all,keys=dnd_buc_list,columns=c("ENSEMBL","UNIPROT"),keytype="ENSEMBL")
dnd_buc_kegg<-enrichKEGG(gene = uni_dnd_buc$UNIPROT,organism = "dre",pAdjustMethod = "BH",pvalueCutoff = 0.01,keyType = "uniprot")
#wt_dnd
wt_dnd <- mutate(diff_wt_dnd,GeneID=rownames(diff_wt_dnd))
wt_dnd_list <- as.character(wt_dnd$GeneID)
go_wt_dnd <- AnnotationDbi::select(ath_all,keys=wt_dnd_list,columns=c("ENSEMBL","SYMBOL"),keytype="ENSEMBL")
BP_wt_dnd <- enrichGO(gene=wt_dnd_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
all_wt_dnd <- enrichGO(gene=wt_dnd_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="all",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
barplot(all_wt_dnd,split='ONTOLOGY')+facet_grid(ONTOLOGY~.,scale='free')
diff_wt2 <- subset(res_wt_dnd, padj < 0.05 & log2FoldChange > 0 )
diff_wt2 <- as.data.frame(diff_wt2)
wt2 <- mutate(diff_wt2,GeneID=rownames(diff_wt2))
wt2_list <- as.character(wt2$GeneID)
go_wt2 <- AnnotationDbi::select(ath_all,keys=wt2_list,columns=c("ENSEMBL","SYMBOL"),keytype="ENSEMBL")
BP_wt2 <- enrichGO(gene=wt2_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
barplot(BP_wt2,showCategory=15)

diff_dnd2 <- subset(res_wt_dnd, padj < 0.05 & log2FoldChange < 0 )
diff_dnd2 <- as.data.frame(diff_dnd2)
dnd2 <- mutate(diff_dnd2,GeneID=rownames(diff_dnd2))
dnd2_list <- as.character(dnd2$GeneID)
go_dnd2 <- AnnotationDbi::select(ath_all,keys=dnd2_list,columns=c("ENSEMBL","SYMBOL"),keytype="ENSEMBL")
BP_dnd2 <- enrichGO(gene=dnd2_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.1,readable=TRUE)
barplot(BP_dnd2,showCategory=15)
#wt_buc
wt_buc <- mutate(diff_wt_buc,GeneID=rownames(diff_wt_buc))
wt_buc_list <- as.character(wt_buc$GeneID)
go_wt_buc <- AnnotationDbi::select(ath_all,keys=wt_buc_list,columns=c("ENSEMBL","SYMBOL"),keytype="ENSEMBL")
BP_wt_buc <- enrichGO(gene=wt_buc_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
all_wt_buc <- enrichGO(gene=wt_buc_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="all",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
dotplot(all_wt_buc,split='ONTOLOGY')+facet_grid(ONTOLOGY~.,scale='free')



diff_wt3 <- subset(res_wt_buc, padj < 0.05 & log2FoldChange > 0 )
diff_wt3 <- as.data.frame(diff_wt3)
wt3 <- mutate(diff_wt3,GeneID=rownames(diff_wt3))
wt3_list <- as.character(wt3$GeneID)
go_wt3 <- AnnotationDbi::select(ath_all,keys=wt3_list,columns=c("ENSEMBL","SYMBOL"),keytype="ENSEMBL")
BP_wt3 <- enrichGO(gene=wt3_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.05,readable=TRUE)
barplot(BP_wt3,showCategory=15)

diff_buc2 <- subset(res_wt_buc, padj < 0.05 & log2FoldChange < 0 )
diff_buc2 <- as.data.frame(diff_buc2)
buc2 <- mutate(diff_buc2,GeneID=rownames(diff_buc2))
buc2_list <- as.character(buc2$GeneID)
go_buc2 <- AnnotationDbi::select(ath_all,keys=buc2_list,columns=c("ENSEMBL","SYMBOL"),keytype="ENSEMBL")
BP_buc2 <- enrichGO(gene=buc2_list,keyType = "ENSEMBL",OrgDb= ath_all, ont="BP",pAdjustMethod="BH",pvalueCutoff=0.05,qvalueCutoff=0.1,readable=TRUE)
barplot(BP_buc2,showCategory=15)
